### ISSUE TITLE
bot cannot bid

### ISSUE THREAD

**Issue by Ye-Lon** [dogancana/futbot#22]
**/invest/low-players** works without failure, but with **/invest/good-auctions**, I always get the following error:

> 2019-10-18T19:37:19.357Z [FUTBOT] info: [Invest:GoodAuction]: James Rodríguez, (85) bidding for 6500, Expires 55, Buynow 25000
> 2019-10-18T19:37:25.757Z [FUTBOT] error: [FUT]: 461 put https://utas.external.s2.fut.ea.com/ut/game/fifa20/trade/259659840579/bid {"bid":6500} Request failed with status code 461 "Permission Denied"
> 2019-10-18T19:37:25.758Z [FUTBOT] error: [Invevst:GoodAuction]: bid failed for James Rodríguez, (85) with bid amount 6500. Reason: undefined

Within two hours uptime, not one single bet got through.

**Comment by dogancana** [comment]
This error happens when there is already a better bet. Because this job looks for auctions around 1 min left and it's hard to get one. But the default profit margin is around 20%, which is fairly high. 

In the weekend I'll try this with different profitMargin values. I'll also check if the bot is too slow to bid. If you wish to try it yourself, you can use the bot in dev mode and change line 11 in this file:
https://github.com/dogancana/futbot/blob/master/lib/invest/jobs/good-auction-investor.ts

I'll make this configurable in the weekend as well.

**Comment by Ye-Lon** [comment]
Alright, thanks a lot!
Loving the frequent updates <3

**Comment by dogancana** [comment]
Will be closed by: https://github.com/dogancana/futbot/issues/29
